### ISSUE TITLE
Error in section 4.3 dot notation macro

### ISSUE THREAD

**Issue by wluker** [greghendershott/fear-of-macros#15]
If I use the macro code for accessing a nested hash table using hash.key.key I notice some lexical scope errors:

    ;; works as expected
    (define js (hasheq 'a (hasheq 'b (hasheq 'c "value0"))))
    (hash.refs js.a.b.c)
    ;; oops! does not access the let bound js, but instead the top level js
    (let ((js (hasheq 'a (hasheq 'b (hasheq 'c "value1")))))
      (hash.refs js.a.b.c))
    ;; unbound identifier error
    (let ((js2 (hasheq 'a (hasheq 'b (hasheq 'c "value2")))))
      (hash.refs js2.a.b.c))

I believe the fix could be:

    (define-syntax (hash.refs stx)    
      (syntax-case stx ()      
        ; If the optional ‘default' is missing, assume it's #f.
        [(_ chain)
         ;; *** we need to keep the syntax context from the original input syntax, not generate 
         ;; *** a new syntax context with the macro recursion
         (datum->syntax stx (syntax->datum #'(hash.refs chain #f)))]
        [(_ chain default)
         (let ([xs (map (lambda (x) (datum->syntax stx (string->symbol x)))
                        (regexp-split #rx"\\." (symbol->string (syntax->datum #'chain))))])
           (with-syntax ([h (car xs)]
                         [ks (cdr xs)])
             #'(hash-refs h 'ks default)))]))
But I'm not sure how to replace (datum->syntax stx (syntax->datum #'(hash.refs chain #f)) with something a little more racketish or descriptive.

Thanks for writing this, it's been quite useful in my learning process.

**Comment by greghendershott** [comment]
Thanks for pointing this out!

I think the fix is simpler:

```
 (define-syntax (hash.refs stx)
   (syntax-case stx ()
     ;; If the optional `default' is missing, assume it's #f.
     [(_ chain)
      #'(hash.refs chain #f)]
     [(_ chain default)
      (let ([xs (map (lambda (x)
-                      (datum->syntax stx (string->symbol x)))
+                      (datum->syntax #'chain (string->symbol x)))
                     (regexp-split #rx"\\."
                                   (symbol->string (syntax->datum #'chain))))])
        (with-syntax ([h (car xs)]
                      [ks (cdr xs)])
          #'(hash-refs h 'ks default)))]))

```
In other words, in something like `(hash.refs js.a.b.c)`, use the lexical context of the `js.a.b.c` syntax not the overall `(hash.refs js.a.b.c)`.

**Comment by greghendershott** [comment]
Also I might rewrite things a bit more to:
- name some intermediate results
- use `for/list`
- use `format-id` since it's introduced by this point

```
(define-syntax (hash.refs stx)
  (syntax-case stx ()
    ;; If the optional `default' is missing, assume it's #f.
    [(_ chain)
     #'(hash.refs chain #f)]
    [(_ chain default)
     (let* ([chain-str (symbol->string (syntax->datum #'chain))]
            [ids (for/list ([str (in-list (regexp-split #rx"\\." chain-str))])
                   (format-id #'chain "~a" str))])
       (with-syntax ([hash-table (car ids)]
                     [keys       (cdr ids)])
         #'(hash-refs hash-table 'keys default)))]))
```

I think that's overall clearer Racket code?

**Comment by wluker** [comment]
This last rewrite is much easier to understand, at least for me.
Thanks!

On Tue, Apr 21, 2015 at 10:19 AM, Greg Hendershott <notifications@github.com

**Comment by greghendershott** [comment]
Great. I'll push a commit with that change. Thanks again for pointing this out!
