### ISSUE TITLE
hash.refs macro with errors

### ISSUE THREAD

**Issue by bencef** [greghendershott/fear-of-macros#17]
https://github.com/greghendershott/fear-of-macros/blob/27fc80861aab7e7ba9eea88e3fb3cb309c9c3a2c/index.rkt#L1210

chain is not matched here.

also the full version raises a syntax error unconditionally

(very good writeup btw. thanks)

**Comment by lojic** [comment]
I just ran into the extra "(raise-syntax-error #f "Expected hash.key0[.key1 ...] [default]" stx #'chain)" in the second version of hash.refs. See commented out line below:

```
(define-syntax (hash.refs stx)
    (syntax-case stx ()
      ; Check for no args at all
      [(_)
       (raise-syntax-error #f "Expected hash.key0[.key1 ...] [default]" stx #'chain)]
      ; If the optional ‘default' is missing, use #f.
      [(_ chain)
       #'(hash.refs chain #f)]
      [(_ chain default)
;       (raise-syntax-error #f "Expected hash.key0[.key1 ...] [default]" stx #'chain)
       (let* ([chain-str (symbol->string (syntax->datum #'chain))]
              [ids (for/list ([str (in-list (regexp-split #rx"\\." chain-str))])
                     (format-id #'chain "~a" str))])
         ; Check that we have at least hash.key
         (unless (and (>= (length ids) 2)
                      (not (eq? (syntax-e (cadr ids)) '||)))
           (raise-syntax-error #f "Expected hash.key" stx #'chain))
         (with-syntax ([hash-table (car ids)]
                       [keys       (cdr ids)])
           #'(hash-refs hash-table 'keys default)))]))
```

**Comment by greghendershott** [comment]
Thanks for reporting this! Thanks @leafac for fixing this in #19.

As I commented on that PR: The prose here notes that adding error-handling code is tedious and obscures the main code -- good reasons to use `syntax-parse` instead. I inadvertently demonstrated another reason here: Error-handling code can be buggy. :grinning:.
