### ISSUE TITLE
unnecessary #` in "4.1.4 Another example" ?

### ISSUE THREAD

**Issue by xuchunyang** [greghendershott/fear-of-macros#27]
`` #` `` occurs in [4.1.4 Another example](http://www.greghendershott.com/fear-of-macros/pattern-matching.html#%28part._.Another_example%29) for the first time without any explanation, it seems unnecessary since `#'` is enough.

**Comment by greghendershott** [comment]
Good point.

**Comment by greghendershott** [comment]
Huh. Not sure why GitHub didn't auto-close this from the commit message. Closing manually.
