### ISSUE TITLE
syntax-e vs syntax->datum in 4.1.4

### ISSUE THREAD

**Issue by nadeemabdulhamid** [greghendershott/fear-of-macros#33]
In [4.1.4](http://www.greghendershott.com/fear-of-macros/pattern-matching.html#%28part._.Another_example%29), why does it use  syntax-e all of a sudden instead of  syntax->datum like in the previous definitions in the section?

**Comment by greghendershott** [comment]
`syntax-e` and `syntax->datum` were discussed earlier, in [3.1](http://www.greghendershott.com/fear-of-macros/Transform_.html#%28part._.What_s_the_input_%29): `syntax->datum` is `syntax-e` applied recursively.

You could use `syntax->datum` here instead. But using `syntax-e` expresses that we expect the syntax to be an identifier that results in a symbol. And if it isn't, there will be a compile-time error.

(The error message will talk about stuff inside the macro implementation, which isn't very helpful to a user of the macro. (We discuss that later. Hint: Using `syntax-parse` with the `id` class would be wonderful.) But at least it will be most proximate to the problem inside the implementation, i.e. it will "go wrong quicker".)

Does that help?

**Comment by nadeemabdulhamid** [comment]
OK, I see. It looks to me like the compile-time error is the same, whether you use `syntax->datum` or `syntax-e`, but I guess avoiding the recursive application is a little more efficient, perhaps. It was just that the earlier definitions of `hyphen-define/...` in the sections above all used `syntax->datum` but at that point it switches to `syntax-e` and I wasn't sure if there was some special reason that `syntax->datum` couldn't be used there as well. Thanks!
