### ISSUE TITLE
unbounded chain in revised hash.refs macros, section 4.3

### ISSUE THREAD

**Issue by nadeemabdulhamid** [greghendershott/fear-of-macros#34]
In the error-handling version of hash.refs in 4.3, in:

````
; Check for no args at all
[(_)
 (raise-syntax-error #f "Expected hash.key0[.key1 ...] [default]" stx #'chain)]
````

the `chain` variable is not bound in the pattern for this case, so the whole sub-expr argument for `raise-syntax-error` should probably be omitted:

````
 (raise-syntax-error #f "Expected hash.key0[.key1 ...] [default]" stx)]
````

**Comment by greghendershott** [comment]
Good catch; thanks.
