### ISSUE TITLE
Emacs comment in Section 4.1

### ISSUE THREAD

**Issue by mikeurbach** [greghendershott/fear-of-macros#39]
There is a note about DrRacket's Macro Expander:

> Even if you prefer mostly to use Emacs, this is a situation where it’s definitely worth temporarily using DrRacket for its Macro Stepper.

I just happened to start using your Emacs racket-mode macro expander functionality just yesterday, and read Fear of Macros for the first time today. I think the macro expander in racket-mode works great! Maybe the comment could plug racket-mode, because for me at least, I see no reason to leave Emacs while debugging macros.

**Comment by greghendershott** [comment]
Thanks!

I think this text predates `racket-stepper-mode` being added.

In general I prefer its diff-style presentation.

Having said that, DrRacket's stepper is still better for inspecting all the properties of syntax objects (in its rightmost pane). Sometimes that information is very important. Up in the Emacs front end, `racket-stepper-mode` is dealing only with plain text results, and doesn't have access to syntax objects. Until this is improved someday (?) I think I'll continue to err on the side of "modesty".

**Comment by mikeurbach** [comment]
Fair enough! I guess I was just a little excited (maybe recency bias) to note that there is _an_ option for those of us who do prefer Emacs.
