### ISSUE TITLE
Zen saying translation is incorrect

### ISSUE THREAD

**Issue by anton-bannykh** [greghendershott/fear-of-macros#9]
I believe the middle part of the translation in the epilogue is incorrect. The code
(not (and (eq? 'mountains 'mountains)
                          (eq? 'rivers 'rivers)))
is equivalent (semantically) to "mountains are not mountains, OR rivers are not rivers", 
whereas the actual words are: "mountains are not mountains, AND rivers are not rivers"

P.S. Sorry for bothering you, I just thought it would be funny to mention the fact.

**Comment by greghendershott** [comment]
Commit 88f07c9 moots
